### ISSUE TITLE
UI finalisation - 1st version

### ISSUE THREAD

**Issue by biocom** [gnosis/safe-cmm-app-react#13]
# Description
Finalise the UI design for the CMM Safe app. Should include implementation of acquired feedback.

---

# Tasks
- [x] Review tooltips: Text and also design (Sasha)
- [x] Review explanation text on the right (Rafa)
- [ ] Show modal on click first TX, to explain the sequence.
- [ ] Optimise the TX. flow as much as possible. Currently has some friction. In part because of how the clickable prototype has been setup on inVision.
- [x] Deployed strategies -> STRATEGY NOW (tab) view - Shows the current balances per bracket + value now vs. HODL
- [x] Deployed strategies -> TRADES (tab) view - Shows a list of recent trades + an option to export trades to a file.
- [x] Deployed strategies -> DEPLOYED PARAMS (tab) view - Shows the parameters used to initially deploy the strategy.
- [ ] Review colour scheme, based on Sasha's new guidelines.

---
# ETA
Estimated end of week (Friday 21st of August)

**Comment by andre-meyer** [comment]
Outdated - Create new ticket for individual tasks and not one "design ticket" :)
